title: Hongtao Lin's Homepage
page-top-title: Hongtao Lin
top-section-bg-text: Immunology
home-subtitle: Hongtao Lin&ensp;|&ensp;林鸿滔
copyright-text: '&copy; Hongtao Lin 2025-2029. All Rights Reserved.'
